const list = [
    {
      id: 1,
      title: "Coconut Shell decorator",
      author: "Coconut shell has a high hardness and micro porosity which increases its durability and absorption and retention capacity. The raw material needed is just fine quality of coconut shell which is obtained from coconut trees.",
      price: 1000,
      img: "https://www.apccsec.org/public/files/image/handicrafts.jpg",
      amount: 1,
    },
    {
      id: 2,
      title: "Coconut shell spoon",
      author: "The objective of the project was to design and develop a new range of cooking accessories for an upscale market segment; using coconut shell, bamboo, wood and metal",
      price: 900,
      img: "https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/5cfc3273097221.5bfe4fb1d0ea8.jpg",
      amount: 1,
    },
    {
      id: 3,
      title: "Coir",
      author: "Coir (pronounced COY-er) comes from coconuts. It's what makes up the fibrous husks of the inner shell of the coconut and is used for all sorts of products, including rugs, ropes, brushes, and even upholstery stuffing.",
      price: 500,
      img: "https://www.apccsec.org/public/files/image/coir.jpg",
      amount: 1,
    },
    {
      id: 4,
      title: "HANDICRAFTS",
      author: "A handicraft, sometimes more precisely expressed as artisanal handicraft or handmade, is any of a wide variety of types of work where useful and decorative objects are made completely by one’s hand or by using only simple, non-automated related tools like scissors, carving implements, or hooks",
      price: 1000,
      img: "https://5.imimg.com/data5/SELLER/Default/2021/5/HI/YV/AW/87869762/handicraft-500x500.jpg",
      amount: 1,
    },
    {
      id: 5,
      title: "Handicrafts",
      author: "Rajdhani Marble Suppliers (RMS) is a well-known Manufacturer, Exporter and Supplier of Marble Products in Mumbai & international market. The wide range of the Marble Products, offered by the company, is inclusive of Marble Fountains, Marble Jali, Marble Qibla, Marble Flower Stands, Marble Bed, Marble Palki and Marble Tables",
      price: 1400,
      img: "https://5.imimg.com/data5/QL/TB/GLADMIN-57177852/handicrafts-500x500.png",
      amount: 1,
    },
    {
      id: 6,
      title: "Painting",
      author: "Wood is an Ingenious art of form which combines the intricacy of Bharatnatyam Painting with the delightful creative strains of a work of art. This involves using wood pieces in their natural colors and textures, delicately cutting and creating the best composition and presenting it in the required theme. The result is the master piece that is interesting too, owing to its.",
      price: 1350,
      img: "https://5.imimg.com/data5/XE/UY/MY-292984/bharatnatyam-9-x-10-500x500.jpg",
      amount: 1,
    },
    {
      id: 7,
      title: "Bharatnatyam ",
      author: "Surabhi Handmade is one of the leading Manufacturer, Wholesaler Trader, Retailer and Service Provider of Canvas Painting, Acrylic Painting, Fabric Hand Painting Services, Oil Painting Service etc.",
      price: 2000,
      img: "https://5.imimg.com/data5/SELLER/Default/2021/1/VB/NO/TK/115638384/surabhiartstudio-cjz2ynobx7l--500x500.jpg",
      amount: 1,
    },
    {
      id: 8,
      title: "Bamboo Basket",
      author: "Surabhi Handmade is one of the leading Manufacturer, Wholesaler Trader, Retailer and Service Provider of Canvas Painting, Acrylic Painting, Fabric Hand Painting Services, Oil Painting Service",
      price: 2800,
      img: "https://www.ethicaonline.com/wp-content/uploads/2018/02/WhatsApp-Image-2018-02-06-at-163941-768x612.jpg",
      amount: 1,
    },
    {
      id: 9,
      title: " Bamboo Box ",
      author: "Categories: Bamboo Box, Bamboo Products, Other Bamboo Handicrafts",
      price: 800,
      img: "https://www.ethicaonline.com/wp-content/uploads/2022/05/WhatsApp-Image-2022-03-19-at-5.31.05-PM.jpeg",
      amount: 1,
    },
    {
      id: 10,
      title: "bag",
      author: "Categories: Jute Bags, Jute Products, Handicrafts, Jute Bag, Jute product",
      price: 850,
      img: "https://www.ethicaonline.com/wp-content/uploads/2023/08/WhatsApp-Image-2023-08-23-at-12.23.37-PM-1.jpeg",
      amount: 1,
    },
    {
      id: 11,
      title: "clock",
      author: "Crafted of wood and wood composite. Real wood panel finish. Requires one AA baterry; battery not included. Comes ready for world mount; not additional hanging hardware required.",
      price: 1200,
      img: "https://www.ethicaonline.com/wp-content/uploads/2018/03/6-1.jpg",
      amount: 1,
    },
    {
      id: 12,
      title: "Bamboo Ring",
      author: "bCategories: Bamboo Baskets, Bamboo Products Bamboo Basket, Bamboo Products, Handicrafts",
      price: 1500,
      img: "https://www.ethicaonline.com/wp-content/uploads/2022/04/WhatsApp-Image-2021-11-14-at-5.45.25-PM.jpeg",
      amount: 1,
    },
];

export default list;